### ISSUE TITLE
Negative relevance in regression?

### ISSUE THREAD

**Issue by vedhas** [sebastian-lapuschkin/lrp_toolbox#13]
### The relevance value is always positive right? 
If a certain feature is responsible for **reducing** the regression output big time (therefore highly relevant), would this be captured with high negative relevance? Definition 2 in [Explaining nonlinear classification decisions with deep Taylor decomposition](https://www.sciencedirect.com/science/article/pii/S0031320316303582) would not allow this as I see it. 

### As for my [regression experiment](https://github.com/sebastian-lapuschkin/lrp_toolbox/issues/12) though, I do see negative R values!

I summed the R values (for the input features, across all the good predictions = samples for which prediction error is less than some tolerance value), there are negaitve values in the resultant summation(R) vector. This is true for `R = nn.lrp(ypred)` and `R = nn.lrp(ypred, 'alphabeta', 2.)` and `R = nn.lrp(ypred, 'epsilon', 1.)`  --> `R = R.sum(axis=0)` (where `ypred=nn.forward(xs[selectedIndices])`) 

Making all the regression labels positive (by adding a constant term) still gave me the negative values in R.sum(axis=0)

**Comment by sebastian-lapuschkin** [comment]
Relevance via LRP is not always positive, as you understood correctly.
In a nutshell, LRP generalizes the interpretability which is inherent in simple linear models, but for deeper, non-linear models. Using LRP you can get positive relevance for pixels/neurons if those pixels/neurons indicate your analyzed output class or increase some regression output and conversely negative values in the opposit cases.

---

DTD is a special case to LRP, which brings along additional assumptions and thus behaves differently.
Same is for alpha/beta decompositions, should this variant be used for each and every layer in the net. alpha/beta assumes your outputs to be (positive)activations.
We advise for relu-like (conv)nets to use epsilon for numerical reasons for dense layers and alpha=2 or alpha=1 for conv layers below.

---

Adding a constant value to force all your regression activations to be positive is similar to using a bias neuron which activates in the forward pass and thus also should absorb some relevance. if you see R.sum() < 0, your bias might be too strong and the model tries to counteract its activation via the learned weights.

---

end note:
pair eps or (if numerically sable) "vanilla" lrp with dense layers.
(optionally) use alpha/beta for conv layers. alpha/beta treats activating and inhibiting forward messages `x[i]w[i,j]` independently. with alpha (and tied to that beta) you can control the semantics of that decomposition. E.g. alpha=1 (beta=0) yields the Excitation Backprop algorithm as a special case of LRP, which only shows what makes an upstream neuron you analyze fire. if you increase beta,  you start adding inhibitory neuron interactions into the mix of your analysis.

E.g. in [Lapusckin et al, ICCV 2017](https://www.researchgate.net/profile/Sebastian_Lapuschkin/publication/319312236_Understanding_and_Comparing_Deep_Neural_Networks_for_Age_and_Gender_Classification/links/59f5a25f0f7e9b553ebbf90b/Understanding-and-Comparing-Deep-Neural-Networks-for-Age-and-Gender-Classification.pdf) I used alpha=2, beta=1 for conv layers and epsilon for dense layers for all models (AlexNet, GoogleNet, VGG16). Blue areas show negative relevance, or input info contradicting the predicted class. Red areas identify features which speak for the predicted class. In the last figure that means that old people don't smile enough in the dataset.

**Comment by vedhas** [comment]
Thanks!
