### ISSUE TITLE
Alpha-Beta LRP not always conservative

### ISSUE THREAD

**Issue by baldassarreFe** [sebastian-lapuschkin/lrp_toolbox#19]
The alpha-beta rule for LRP from Eq. 60 is not always conservative, here's some examples for the [Linear module](https://github.com/sebastian-lapuschkin/lrp_toolbox/blob/cb6a4926ac821b342f4baacadc70b2a3bf3bca41/python/modules/linear.py):

### Zeros in the input

If the output contains zeros, the `_alphabeta_lrp_slow` method that implements the original Eq. 60 returns some `NaN`s due to divisions by zero.
Note that this case is very frequent if the previous activation is a ReLU.

```python
import numpy as np
from modules import Linear

X = np.array([
  [0., 0.],
  [0., 1.],
  [1., 0.],
  [2., 4.]
])
linear = Linear(2, 1)
linear.W = np.array([
  [-1.],
  [+1.]
])
linear.B = np.zeros_like(linear.B)
Y = linear.forward(X)
print(Y)
>>> [[ 0.]
>>>  [ 1.]
>>>  [-1.]
>>>  [ 2.]]

R_y = np.where(Y != 0, 1, 0)
print(R_y)
>>> [[0]
>>>  [1]
>>>  [1]
>>>  [1]]

R_x = linear._alphabeta_lrp_slow(R_y, alpha=2)
print(R_x)
>>> [[nan nan]
>>>  [nan nan]
>>>  [nan nan]
>>>  [-1.  2.]]
```

The method `_alphabeta_lrp` [adds a small number to denominator](https://github.com/sebastian-lapuschkin/lrp_toolbox/blob/cb6a4926ac821b342f4baacadc70b2a3bf3bca41/python/modules/linear.py#L243) to avoid dividing by zero.
However the zeros remain at the numerator and break the conservation property:

```python
R_x = linear._alphabeta_lrp(R_y, alpha=2)
print(R_x)
>>> [[ 0.  0.]
>>>  [ 0.  2.]
>>>  [-1.  0.]
>>>  [-1.  2.]]
```

### Zeros in the weights

If the weight matrix contains zeros, a similar thing happens, with the zeros propagating to the numerators of the alpha and beta parts and breaking the balance between the two.
Again, this can happen frequently for networks that are trained with L1 regularization.

```python
X = np.array([
  [1., 1.],
  [1., 2.]
])
linear = Linear(2, 1)
linear.W = np.array([
  [ 0.],
  [+1.]
])
linear.B = np.zeros_like(linear.B)
Y = linear.forward(X)
print(Y)
>>> [[1.]
>>>  [2.]]

R_y = np.where(Y != 0, 1, 0)
print(R_y)
>>> [[1]
>>>  [1]]

R_x = linear._alphabeta_lrp(R_y, alpha=2)
print(R_x)
>>> [[0. 2.]
>>>  [0. 2.]]
```

Can you suggest a way to mantain the conservation property in these cases? How is this done in the experiments that followed the initial paper?

**Comment by sebastian-lapuschkin-sideprojects** [comment]
Hi @baldassarreFe ,

this is a known issue with the alpha-beta-decomposition with both alpha != 0 and beta !=0 (i.e. alpha > 1) and the case that either no inhibitations (z_{ij} < 0) or activations (z_{ij} > 0) exist for output neurons.

a simple 1d toy example illustrates that already, with
w = 1
x = 1
alpha=2; beta = -1

y = w*x = 1 = R_y

here, we only have one z_{ij} = z = 1, which means only activations, no inhibitions. this only triggers the alpha-weighted component of the alpha-beta decomposition formula and does not touch the beta-weighted term which should provide a counter-weight. We end up with

R_x = (alpha * z^+ * R_y) + (beta * z^- *R_y) = (2 * 1 * 1)  + (-1 * 0 * 1) = 2

which effectively doubles relevance. A similar effect can be observed if no activations and only inhibitions exists for particular neurons.

One way to work around that would be to check for this kind of occurrence and then select for those particular neurons default parameters (e.g. alpha=1) depending on the case to ensure conservativity.


unfortunately we have not provided that  in writing in the past. 
Thank you for pointing it out again.
I sincerely hope that explanation helps. You are very welcome to contribute, btw :)

**Comment by sebastian-lapuschkin** [comment]
whoops, wrong account ( @sebastian-lapuschkin-sideprojects ) . still me

**Comment by baldassarreFe** [comment]
Thanks for the explanation! I imagined something similar when I first read the equations, but I did not think of that workaround. I'll see if works for my case, hopefully I'll get some interesting explanations.

About contributions, I'll keep an eye on the issue page if something comes up that I can work on ;)
