### ISSUE TITLE
Issues about reading the model

### ISSUE THREAD

**Issue by TestingAIGroup** [sebastian-lapuschkin/lrp_toolbox#24]
Thank you very much for sharing your code.
I am really interested in your work. 
I first converted the Keras model (.h5) to txt. The dataset is CIFAR-10. An Error occurred when reading the txt model.
Here are the source codes:
model_path = model_folder + '/' + self.model_name
write(model_path, model_path, num_channels=test_inputs[0].shape[-1], fmt='keras_txt')
lrpmodel = read(model_path + '.txt', 'txt') 
I got the following message:
![image](https://user-images.githubusercontent.com/18699423/139845305-e9c96cb5-ee91-4d34-aa14-4abd0c76d7b7.png)

Could you please help me to solve this issue?
Thank you very much.

**Comment by sebastian-lapuschkin** [comment]
Dear @SBR-Miner, 

this library is pretty old and ist origins predate the wide-spread use of Keras/Tensorflow and Pytorch in Deep Learning. Thus, there is no direct support for both frameworks, and development has halted. The last (and very much likely the final) release mostly was a compatibility update for the Caffe-branch of the probject using containerization via singularty.

If you seek to apply LRP to your models, I recommend https://github.com/albermax/innvestigate for Keras/Tensorflow 2.0 (the transition to tf2.0 is ready, you should bother @adrhill to already release it :) )

For Pytorch, please use https://github.com/chr5tphr/zennit

best
