### ISSUE TITLE
Work with document

### ISSUE THREAD

**Issue by iij0** [sebastian-lapuschkin/lrp_toolbox#4]
Hi,

I am also interested in the prediction of the type of document. Do you have any plan to provide example for this application?

**Comment by sebastian-lapuschkin** [comment]
Hi,

there is currently no plan to build an example dedicated to text processing. However, there is this paper (under review) from our lab / TU Berlin on the topic: https://arxiv.org/pdf/1612.07843.pdf

The authors use Word2Vec to embed documents into vector space. The embedded features are then fed into a DNN model for prediction. For an explanation, LRP is used  for the DNN-part of the model as you would with the toolbox. The Word2Vec embedding is resolved akin to the LRP-decomposition of a generic Bag of Words mapping function (see our PLOS One publication. Direct link to relevant Section: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0130140#sec006 ). The Word2Vec explanation step is, in the end, just an application of the LRP decomposition rules to the mapping function. Should you use any other text based mapping, e.g. n-grams, you can naturally apply the decomposition rules of LRP and implement them. 

I will get in touch with the author of the paper behind the first link and ask for the model. Given the amount of expected work for including a NLP example based on that model into to the toolbox is limited, I will inclulde it. No promises though :)

Cheers,

**Comment by sebastian-lapuschkin** [comment]
Update:

The code and models used for the paper https://arxiv.org/pdf/1612.07843.pdf will be published, as soon as it has been officially released. 

Can't say when though.

Due to the size of the Word2Vec lookup table I will not include example code for NLP into the toolbox in forseeable time, since everything else after Word2Vec is already covered by existing code.
